version: '3.8'

services:
  langchain_agent:
    build: .
    ports:
      - "5001:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    volumes:
      - ./cheatsheets:/app/cheatsheets

